export const tableData = [
  {
    value: "10",
    date: "5",
    user: "Anna",
    comment: "correct",
  },
  {
    value: "8",
    date: "10",
    user: "Olena",
    comment: "final",
  },
  {
    value: "9",
    date: "3",
    user: "Taras",
    comment: "last",
  },
  {
    value: "4",
    date: "2",
    user: "Petro",
    comment: "lost",
  },
  {
    value: "9",
    date: "3",
    user: "Taras",
    comment: "last",
  },
  {
    value: "4",
    date: "2",
    user: "Petro",
    comment: "lost",
  },
  {
    value: "9",
    date: "3",
    user: "Taras",
    comment: "last",
  },
  {
    value: "4",
    date: "2",
    user: "Petro",
    comment: "lost",
  },
  {
    value: "9",
    date: "3",
    user: "Taras",
    comment: "last",
  },
  {
    value: "4",
    date: "2",
    user: "Petro",
    comment: "lost",
  },
  {
    value: "9",
    date: "3",
    user: "Taras",
    comment: "last",
  },
  {
    value: "4",
    date: "2",
    user: "Petro",
    comment: "lost",
  },
  {
    value: "9",
    date: "3",
    user: "Taras",
    comment: "last",
  },
  {
    value: "4",
    date: "2",
    user: "Petro",
    comment: "lost",
  },
  // {
  //   item: "dinner",
  //   action: "make",
  //   name: "Andrii",
  //   gender: "male",
  // },
  // {
  //   item: "shower",
  //   action: "take",
  //   name: "Alex",
  //   gender: "male",
  // },
  // {
  //   item: "dessert",
  //   action: "make",
  //   name: "Zhanna",
  //   gender: "female",
  // },
  // {
  //   item: "picture",
  //   action: "make",
  //   name: "Petro",
  //   gender: "male",
  // },
];
